name: Coverage
on: push

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Generate cov report
      run: make py_test

    - name: Upload to codecov
      uses: codecov/codecov-action@v2